'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace WebApplication3


	Partial Public Class _Default

		''' <summary>
		''' table1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected table1 As Global.System.Web.UI.WebControls.Table

		''' <summary>
		''' TableRow2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TableRow2 As Global.System.Web.UI.WebControls.TableRow

		''' <summary>
		''' TableCell1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TableCell1 As Global.System.Web.UI.WebControls.TableCell

		''' <summary>
		''' Label1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label1 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' dropDownListType control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dropDownListType As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' lblBorderType control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblBorderType As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' borderType control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected borderType As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' Label3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label3 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' DropDownListColor control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected DropDownListColor As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' dropFont control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dropFont As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' TableRow1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TableRow1 As Global.System.Web.UI.WebControls.TableRow

		''' <summary>
		''' textBoxText control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected textBoxText As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' Label4 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label4 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' textBoxHeight control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected textBoxHeight As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' Label5 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label5 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' textBoxFontSize control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected textBoxFontSize As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' checkShowText control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected checkShowText As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' checkShowBorder control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected checkShowBorder As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' checkShowSum control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected checkShowSum As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' Div1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

		''' <summary>
		''' BarCodeControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected BarCodeControl1 As Global.Spire.Barcode.WebUI.BarCodeControl

		''' <summary>
		''' Button1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Button1 As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' Label2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label2 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' lblResult control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblResult As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label8 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label8 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label9 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label9 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label10 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label10 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label11 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label11 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label12 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label12 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label13 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label13 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label14 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label14 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label15 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label15 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label16 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label16 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label17 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label17 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label22 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label22 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label23 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label23 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label6 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label6 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label7 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label7 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label18 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label18 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label19 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label19 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label20 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label20 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Label21 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label21 As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
