'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace WebApplication3


	Partial Public Class SiteMaster

		''' <summary>
		''' HeadContent control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

		''' <summary>
		''' LinkButton1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

		''' <summary>
		''' LinkButton2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LinkButton2 As Global.System.Web.UI.WebControls.LinkButton

		''' <summary>
		''' Label1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label1 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' LinkButton3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LinkButton3 As Global.System.Web.UI.WebControls.LinkButton

		''' <summary>
		''' Label2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label2 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' MainContent control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
	End Class
End Namespace
